[package]
name = "simple-rs"
version = "0.1.0"
authors = ["Devin Jacobs <dbuttonz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.51.1"

[dependencies]
